# syntax=docker/dockerfile:1
FROM node:19-alpine3.15

WORKDIR /app

COPY package*.json ./

RUN npm ci --only=production

COPY . ./

EXPOSE $LOG_LEVEL
EXPOSE $PORT
EXPOSE $TOKEN_KEY
EXPOSE $REDIS_HOST
EXPOSE $REDIS_PORT
EXPOSE $REDIS_UNAME
EXPOSE $REDIS_PWORD
EXPOSE $REDIS_DB
EXPOSE $DEFAULT_GAME_TTL
EXPOSE $DEFAULT_USER_TTL
EXPOSE $DEFAULT_TOKEN_TTL
EXPOSE $ENABLE_SERVER_SOUND



CMD ["npm", "start"]
